<?php


class Collaborateur extends User
{
    protected $id_collab,
              $prenom_collab;

    public function __construct($data = [])
    {
        parent::__construct($data);
    }

    public function hydrate(array $data)
    {
        parent::hydrate($data); // TODO: Change the autogenerated stub
    }

    //  Méthodes

    public function regValid()
    {
        return !(empty($this->nom) || empty($this->prenom_collab) || empty($this->username) || empty($this->password) || empty($this->question) || empty($this->reponse));
    }

    public function majInfoValid()
    {
        return !(empty($this->nom) || empty($this->prenom_collab) || empty($this->username) || empty($this->id_collab));
    }

    public function majPasswordValid()
    {
        return !(empty($this->password) || empty($this->username) || empty($this->id_collab));
    }

    public function repValide()
    {
        return !(empty($this->question) || empty($this->reponse) || empty($this->id_collab));
    }


    // Setters

    public function setId_collab($id_collab)
    {
        $id_collab = (int) $id_collab;

        if ($id_collab > 0)
        {
            $this->id_collab = $id_collab;
        }
    }

    public function setPrenom_collab($prenom_collab)
    {
        if (is_string($prenom_collab))
        {
            $this->prenom_collab = $prenom_collab;
        }
    }

    // Getters

    public function id_collab()
    {
        return $this->id_collab;
    }

    public function prenom_collab()
    {
        return $this->prenom_collab;
    }
}